version: "3.7"
services:
  mysql:
    image: percona:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"

  rabbit:
    hostname: rabbit
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
      - RABBITMQ_DEFAULT_VHOST=vhost
    ports:
      - "5673:5672"
      - "15673:15672"
    
#  pgsql:
#    image: postgres
#    environment:
#      POSTGRES_USER: "postgres"
#      POSTGRES_PASSWORD: "my_password"
#    ports:
#      - "5432:5432"